### ISSUE TITLE
Texts not showing with thaumicbases-3.0.105.30b

### ISSUE THREAD

**Issue by 63502** [Rumaruka/Thaumic-Bases-Unofficial#1]
The Thaumonomicon texts do not show up at all. Item names appear to be just fine though.

**Comment by Rumaruka** [comment]
Screenshot?

**Comment by 63502** [comment]
All of the research texts and titles in the Thaumic Bases tab show up like so(using base research as example):

- research_name.thaumicbases:thaumicbases

As I stated above, only the Thaumonomicon is affected. All Items show with their correct name.

**Comment by Rumaruka** [comment]
I'm don't add Lore for addon, maybe later

**Comment by Rumaruka** [comment]
I know about text. I write later, now I make functions
Close #1

**Comment by Rumaruka** [comment]
Add in Release version
