### ISSUE TITLE
Crops growing extremely slow, and randomly not dropping anything.

### ISSUE THREAD

**Issue by javiarias** [Rumaruka/Thaumic-Bases-Unofficial#10]
I've been playing with the Plax, Metalleat and Lazullia crops for a while in the "Garden of Thaumcraft and Botania" pack, and I've encountered two issues.
Firstly, at least those three crops seem to grow extremely slow, taking more than 24 IRL hours just to grow one single stage.
Second, sometimes the crops don't drop anything, not even seeds, even when they seem to be fully grown (aka bonemeal doesn't change them anymore). I haven't been able to replicate this consistently, though. Sorry :x

Also, the Agricarnation from Botania doesn't work with those crops. It might be a problem with Botania itself, but you never know.
Hope this helped a bit!

**Comment by Rumaruka** [comment]
Eeem
Pack don't update addon
I make fix 24 hours ago

**Comment by javiarias** [comment]
Oh, sorry :x
I'll just wait until the pack's updated, then. Thank you!
