### ISSUE TITLE
Crashes with Thaumcraft 6.1.BETA26 and Forge 14.23.5.2769

### ISSUE THREAD

**Issue by sandalle** [Rumaruka/Thaumic-Bases-Unofficial#11]
Updated to Thaumcraft-1.12.2-6.1.BETA26 (https://minecraft.curseforge.com/projects/thaumcraft/files/2628773) released today and Forge Mod Loader 1.12.2 - 14.23.5.2769 (http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.12.2.html). Using latest release Thaumic Bases 3.2.265.4r.

Thaumic Additions had a similar issue and fixed it with https://gitlab.com/DragonForge/ThaumicAdditions/commit/b8ca6ddd3de392eb0b85d19348458929624e3e49 .

[crash-2018-10-17_19.28.08-client.txt](https://github.com/Rumaruka/Thaumic-Bases-Unofficial/files/2489971/crash-2018-10-17_19.28.08-client.txt)

**Comment by Darkmega18** [comment]
this. also got this. report given to me by vanilla fix.
https://paste.dimdev.org/becocuxobe.mccrash

**Comment by Rumaruka** [comment]
I don't looking API TC 6 beta26
But soon make update

**Comment by Rumaruka** [comment]
Fixed in 3.2.270.4r
