### ISSUE TITLE
Messis (and possibly others) crystals are not possible to be made

### ISSUE THREAD

**Issue by piotrb** [Rumaruka/Thaumic-Bases-Unofficial#14]
in 3.3.310.5r .. I got some research that asked me to supply a messis crystal, but I can't seem to make it . it doesn't work in the crucible or in the alchemy machine.

**Comment by Rumaruka** [comment]
I already make crystal and tested 
```
CrucibleRecipe crystalM = new CrucibleRecipe("TB.EXCHANG", AscpectUtils.crystalEssence(MESSIS), new ItemStack(ItemsTC.nuggets,1,9), new AspectList().add(MESSIS,2));
--
412 | ThaumcraftApi.addCrucibleRecipe(new ResourceLocation("TB.crystalM"), crystalM);
```

**Comment by TehenoPengin** [comment]
Talking with @Rumaruka right now, he fixed this.

**Comment by Rumaruka** [comment]
Fix, checked curse

**Comment by piotrb** [comment]
Very strange then .. perhaps its a conflict with another mod then, are you aware of any known conflicts?

**Comment by Rumaruka** [comment]
Look new update =)

**Comment by piotrb** [comment]
Ah sorry .. didn't realize there was a new update from just now ;)

Also curse wasn't very helpful .. maybe because you gave the file the same filename or something .. I manually installed it just to be sure now ;)

![screen shot 2018-12-29 at 2 12 08 pm](https://user-images.githubusercontent.com/13251/50542509-d4bfe080-0b73-11e9-99ad-bd51ecb5905f.png)

**Comment by piotrb** [comment]
Works now, thanks!

**Comment by Rumaruka** [comment]
@piotrb 
https://minecraft.curseforge.com/projects/thaumic-bases-unofficial/files/2653791

**Comment by quicktinker** [comment]
Wait, so did you fix the fact you can't get certain essences but kept the version number the same?? How do i know if I have the broken one or if i have the fixed one but with another bug?
