### ISSUE TITLE
Aspects used to create some items not Available & very bad English.

### ISSUE THREAD

**Issue by quicktinker** [Rumaruka/Thaumic-Bases-Unofficial#17]
Hi, while playing with this mod I noticed that some of the old aspects, like Sano and Pannus and such, which were used in the old Thaumcraft version but not in the current one are used in the creation of some items. This causes a problem as there is no way to obtain these aspects except through the items they are used to create or through cheating the Essentia in. 
![image](https://user-images.githubusercontent.com/33596312/52799925-b30eb000-3072-11e9-9a35-97c9522e7f32.png)
![image](https://user-images.githubusercontent.com/33596312/52800139-126cc000-3073-11e9-84f3-e16b99449b74.png)

Also, the English in the Thaumiomicon for some of the research pages is exceptionally bad and does not make sense. 
![image](https://user-images.githubusercontent.com/33596312/52800009-d20d4200-3072-11e9-8e55-2496c72a6979.png)

please fix these issues!

**Comment by Rumaruka** [comment]
Version mods

**Comment by quicktinker** [comment]
Sorry! Was in a rush and forgot the version numbers. 
Thaumcraft beta 26 1.12.2 (latest) and tb3.3.310.5r. Latest version of thaumic bases.

**Comment by Rumaruka** [comment]
Okay , I look

**Comment by Rumaruka** [comment]
![2019-03-04_20 19 09](https://user-images.githubusercontent.com/8148679/53742683-011d1380-3ebb-11e9-83a8-4fc99555d2de.png)
Soon fix

**Comment by quicktinker** [comment]
Thank you!
