### ISSUE TITLE
Plax still doesn't grow without bonemeal

### ISSUE THREAD

**Issue by DaedalusGame** [Rumaruka/Thaumic-Bases-Unofficial#19]
Might be missing the grow call in its random tick method

**Comment by Rumaruka** [comment]
Version?

**Comment by DaedalusGame** [comment]
3.3.310.5r

**Comment by Rumaruka** [comment]
Hmmm
https://minecraft.curseforge.com/projects/thaumic-bases-unofficial/files/2685845

**Comment by DaedalusGame** [comment]
Sorry, it's 3.3.345.6r. The version doesn't show correctly ingame.

**Comment by Rumaruka** [comment]
Tested later D:

**Comment by Rumaruka** [comment]
Fixed in new version TBU (Soon)
