### ISSUE TITLE
Planks and logs are both missing ore dictionary tags

### ISSUE THREAD

**Issue by TheDeviantCrafter** [Rumaruka/Thaumic-Bases-Unofficial#20]
Other mods that add threes add the `plankWood` ore dictionary tag to their planks, and the `logWood` tag to their logs. This allows them to be used in recipes that require planks and logs. All of the planks and logs from this mod are missing those tags, so they can't be used in any crafting recipes.

For example, they can't be made into sticks:

![image](https://user-images.githubusercontent.com/18755309/59320270-668b5800-8c93-11e9-9d5c-047697ec0ddd.png)

**Comment by Rumaruka** [comment]
![image](https://user-images.githubusercontent.com/8148679/59966755-32892000-953a-11e9-837f-f6aa477e0a6b.png)
Fixed <3
