### ISSUE TITLE
Crash (bandicoot XD)

### ISSUE THREAD

**Issue by shoverno2** [Rumaruka/Thaumic-Bases-Unofficial#21]
Glow stone dust plant Couse crash.
Maybe only with green thaum lantern.
Sorry, can't show log, not in home.

**Comment by Rumaruka** [comment]
I want crashlog :)

**Comment by shoverno2** [comment]
> I want crashlog :)

here it is =)
`---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2019-06-26 10:34:37 MSK
Description: Batching chunks

java.lang.IllegalStateException: Not building!
    at net.minecraft.client.renderer.BufferBuilder.finishDrawing(BufferBuilder.java:739)
    at net.minecraft.client.renderer.chunk.RenderChunk.postRenderBlocks(RenderChunk.java:514)
    at net.minecraft.client.renderer.chunk.RenderChunk.rebuildChunk(RenderChunk.java:359)
    at net.minecraft.client.renderer.chunk.ChunkRenderWorker.processTask(SourceFile:100)
    at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43)
    at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected level --
  Level name: MpServer
  All players: 1 total; [EntityPlayerSP['Void_Delirium'/45, l='MpServer', x=1045.39, y=5.50, z=15.30]]
  Chunk stats: MultiplayerChunkCache: 16, 16
  Level seed: 0
  Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
  Level generator options: 
  Level spawn location: World: (-108,64,256), Chunk: (at 4,4,0 in -7,16; contains blocks -112,0,256 to -97,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
  Level time: 3287738 game time, 4581871 day time
  Level dimension: 0
  Level storage version: 0x00000 - Unknown?
  Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
  Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
  Forced entities: 2 total; [EntityItem['item.tile.stonebrick'/46, l='MpServer', x=1032.65, y=4.88, z=5.65], EntityPlayerSP['Void_Delirium'/45, l='MpServer', x=1045.39, y=5.50, z=15.30]]
  Retry entities: 0 total; []
  Server brand: fml,forge
  Server type: Integrated singleplayer server

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 7 (amd64) version 6.1
  Java Version: 1.8.0_211, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 1106349304 bytes (1055 MB) / 2722922496 bytes (2596 MB) up to 2884894720 bytes (2751 MB)
  JVM Flags: 3 total; -Xmn128M -Xmx2764M -XX:+UseConcMarkSweepGC
  IntCache: cache: 0, tcache: 0, allocated: 16, tallocated: 56
  FML: MCP 9.42 Powered by Forge 14.23.5.2825 Optifine OptiFine_1.12.2_HD_U_E4_pre1 98 mods loaded, 98 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                                           | Version                     | Source                                        | Signature                                |
       |:------ |:-------------------------------------------- |:--------------------------- |:--------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft                                    | 1.12.2                      | minecraft.jar                                 | None                                     |
       | LCHIJA | mcp                                          | 9.42                        | minecraft.jar                                 | None                                     |
       | LCHIJA | FML                                          | 8.0.99.99                   | forge-1.12.2-14.23.5.2825.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                                        | 14.23.5.2825                | forge-1.12.2-14.23.5.2825.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | creativecoredummy                            | 1.0.0                       | minecraft.jar                                 | None                                     |
       | LCHIJA | itemphysic                                   | 1.4.0                       | minecraft.jar                                 | None                                     |
       | LCHIJA | com.elytradev.movingworld.common.asm.coremod |                             | minecraft.jar                                 | None                                     |
       | LCHIJA | ClientFixer                                  | 1.12.2-1.9                  | minecraft.jar                                 | None                                     |
       | LCHIJA | dsurroundcore                                | 3.5.4.3                     | minecraft.jar                                 | None                                     |
       | LCHIJA | swordskillsapi                               | 1.1.0                       | 1.12.2-SwordSkillsApi-1.1.0.jar               | None                                     |
       | LCHIJA | dynamicswordskills                           | 1.12.2-6.0.1                | 1.12.2-DynamicSwordSkills-6.0.1.jar           | None                                     |
       | LCHIJA | ambience                                     | GRADLE:VERSION-GRADLE:BUILD | Ambience+1.1-10.jar                           | None                                     |
       | LCHIJA | codechickenlib                               | 3.2.2.353                   | CodeChickenLib-1.12.2-3.2.2.353-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | ancientwarfare                               | 1.12.2-2.7.0.704            | ancientwarfare-1.12.2-2.7.0.704.jar           | None                                     |
       | LCHIJA | ancientwarfarestructure                      | 1.12.2-2.7.0.704            | ancientwarfare-1.12.2-2.7.0.704.jar           | None                                     |
       | LCHIJA | ancientwarfarevehicle                        | 1.12.2-2.7.0.704            | ancientwarfare-1.12.2-2.7.0.704.jar           | None                                     |
       | LCHIJA | ancientwarfarenpc                            | 1.12.2-2.7.0.704            | ancientwarfare-1.12.2-2.7.0.704.jar           | None                                     |
       | LCHIJA | ancientwarfareautomation                     | 1.12.2-2.7.0.704            | ancientwarfare-1.12.2-2.7.0.704.jar           | None                                     |
       | LCHIJA | antiqueatlas                                 | 4.5.0                       | antiqueatlas-1.12.2-4.5.0.jar                 | e631d7254e451d0360d0148cb21407d5511d45e9 |
       | LCHIJA | antiqueatlasoverlay                          | 1.2                         | antiqueatlas-1.12.2-4.5.0.jar                 | e631d7254e451d0360d0148cb21407d5511d45e9 |
       | LCHIJA | anvilfix                                     | 1.0.3                       | AnvilFix-1.12.2-1.0.3.jar                     | None                                     |
       | LCHIJA | baubles                                      | 1.5.2                       | Baubles-1.12-1.5.2.jar                        | None                                     |
       | LCHIJA | artifacts                                    | 1.12.2-1.1.0                | Artifacts-1.12.2-1.1.0.jar                    | None                                     |
       | LCHIJA | astikorcarts                                 | 1.12.2-0.1.2.7              | astikorcarts-1.12.2-0.1.2.7.jar               | None                                     |
       | LCHIJA | betterthanmending                            | 1.1.1                       | BetterThanMending-1.1.1.jar                   | None                                     |
       | LCHIJA | biomesoplenty                                | 7.0.1.2427                  | BiomesOPlenty-1.12.2-7.0.1.2427-universal.jar | None                                     |
       | LCHIJA | bonsaitrees                                  | 1.1.2                       | bonsaitrees-1.1.2-b144.jar                    | None                                     |
       | LCHIJA | bookshelf                                    | 2.3.577                     | Bookshelf-1.12.2-2.3.577.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | bmtr                                         | 0.4                         | BringMeTheRings-0.4.jar                       | None                                     |
       | LCHIJA | ctm                                          | MC1.12.2-0.3.3.22           | CTM-MC1.12.2-0.3.3.22.jar                     | None                                     |
       | LCHIJA | chisel                                       | MC1.12.2-0.2.1.35           | Chisel-MC1.12.2-0.2.1.35.jar                  | None                                     |
       | LCHIJA | toughasnails                                 | 3.1.0.139                   | ToughAsNails-1.12.2-3.1.0.139-universal.jar   | None                                     |
       | LCHIJA | comforts                                     | 1.4.1.2                     | comforts-1.12.2-1.4.1.2.jar                   | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
       | LCHIJA | cosmeticarmorreworked                        | 1.12.2-v4a                  | CosmeticArmorReworked-1.12.2-v4a.jar          | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
       | LCHIJA | cosmiclib                                    | 0.4.0                       | CosmicLib-1.12.2-0.4.0.BETA.jar               | d3974446c00f9f1d275edce305771eeddf30c658 |
       | LCHIJA | creativecore                                 | 1.9.9                       | CreativeCore_v1.9.45_mc1.12.2.jar             | None                                     |
       | LCHIJA | movingworld                                  | 1.12-6.342                  | movingworld-1.12-6.342-full (2).jar           | None                                     |
       | LCHIJA | davincisvessels                              | @DVESSELSVER@               | davincisvessels-1.12-6.340-full (2).jar       | None                                     |
       | LCHIJA | dimdoors                                     | 3.0.9+287                   | DimensionalDoors-3.0.9-287.jar                | None                                     |
       | LCHIJA | dummycore                                    | 2.4.112.5.                  | DummyCoreUnofficial-2.4.112.5.jar             | None                                     |
       | LCHIJA | fantasticlib                                 | 1.12.2.012                  | FantasticLib-1.12.2.012.jar                   | None                                     |
       | LCHIJA | dynamicstealth                               | 1.12.2.070                  | DynamicStealth-1.12.2.070.jar                 | None                                     |
       | LCHIJA | eplus                                        | 5.0.176                     | EnchantingPlus-1.12.2-5.0.176 (1).jar         | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | eyesinthedarkness                            | 0.0.5                       | EyesInTheDarkness-0.0.5.jar                   | None                                     |
       | LCHIJA | familiarfauna                                | 1.0.11                      | FamiliarFauna-1.12.2-1.0.11.jar               | None                                     |
       | LCHIJA | fancylamps                                   | 1.1.0                       | fancylamps-1.1.0.jar                          | None                                     |
       | LCHIJA | forgelin                                     | 1.8.2                       | Forgelin-1.8.2.jar                            | None                                     |
       | LCHIJA | globalxp                                     | v1.4.3                      | globalxp-1.12.x-v1.4.3.jar                    | None                                     |
       | LCHIJA | hammercore                                   | 2.0.4.7                     | HammerCore-1.12.2-2.0.4.7.jar                 | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
       | LCHIJA | hardcoredarkness                             | 2.0                         | HardcoreDarkness-MC1.12.2-2.0.jar             | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LCHIJA | thaumcraft                                   | 6.1.BETA26                  | Thaumcraft-1.12.2-6.1.BETA26.jar              | None                                     |
       | LCHIJA | thaumadditions                               | 18r                         | ThaumicAdditions-1.12.2-18r.jar               | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
       | LCHIJA | llibrary                                     | 1.7.18                      | llibrary-1.7.18-1.12.2.jar                    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCHIJA | iceandfire                                   | 1.7.1                       | iceandfire-1.7.1-1.12.2.jar                   | None                                     |
       | LCHIJA | ignitehud                                    | 1.12-b0.1.1                 | ignitehud_1.12-b0.1.1.jar                     | None                                     |
       | LCHIJA | jei                                          | 4.15.0.277                  | jei_1.12.2-4.15.0.277.jar                     | None                                     |
       | LCHIJA | mantle                                       | 1.12-1.3.3.49               | Mantle-1.12-1.3.3.49.jar                      | None                                     |
       | LCHIJA | radixcore                                    | 1.12.x-2.2.1                | RadixCore-1.12.x-2.2.1-universal.jar          | None                                     |
       | LCHIJA | mca                                          | 1.12.2-5.3.1                | MCA-1.12.x-5.3.1-universal.jar                | None                                     |
       | LCHIJA | mobblocker                                   | 1.12-1.5.0                  | mobblocker-1.12-1.5.0.jar                     | None                                     |
       | LCHIJA | moreplayermodels                             | 1.12.2                      | MorePlayerModels_1.12.2(18jan18).jar          | None                                     |
       | LCHIJA | mowziesmobs                                  | 1.5.4                       | mowziesmobs-1.5.4.jar                         | None                                     |
       | LCHIJA | nospawnzone                                  | 1.12.2.1.3                  | NoSpawnZone-1.12.2.1.3 (1).jar                | None                                     |
       | LCHIJA | nei                                          | 2.4.2                       | NotEnoughItems-1.12.2-2.4.2.240-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | twilightforest                               | 3.8.689                     | twilightforest-1.12.2-3.8.689-universal.jar   | None                                     |
       | LCHIJA | tconstruct                                   | 1.12.2-2.12.0.135           | TConstruct-1.12.2-2.12.0.135.jar              | None                                     |
       | LCHIJA | planarartifice                               | 0.13                        | planarartifice-0.13.jar                       | None                                     |
       | LCHIJA | plustic                                      | 7.0.5.2                     | plustic-7.0.5.2.jar                           | None                                     |
       | LCHIJA | pcb                                          | 1.5.0                       | portablecraftbench-1.12.2-1.5.1.jar           | None                                     |
       | LCHIJA | rfp2                                         | 1.12.2-1.1.0                | RealFirstPerson2-1.12.2-1.1.0.jar             | None                                     |
       | LCHIJA | rustic                                       | 1.1.0                       | rustic-1.1.0.jar                              | None                                     |
       | LCHIJA | rusticthaumaturgy                            | 4.4a                        | Rustic+Thaumaturgy-4.4a.jar                   | None                                     |
       | LCHIJA | sereneseasons                                | 1.2.15                      | SereneSeasons-1.12.2-1.2.15-universal.jar     | None                                     |
       | LCHIJA | silentlib                                    | 3.0.13                      | SilentLib-1.12.2-3.0.13+167.jar               | None                                     |
       | LCHIJA | simplemagnet                                 | 1.12.2-1.3.12               | simplemagnet-1.12.2-1.3.12.jar                | None                                     |
       | LCHIJA | tickratechanger                              | 1.0.14                      | TickrateChanger-1.0.14.jar                    | None                                     |
       | LCHIJA | sleepingoverhaul                             | 1.0.0                       | SleepingOverhaul-1.12.2-1.0.0.jar             | d3974446c00f9f1d275edce305771eeddf30c658 |
       | LCHIJA | somanyenchantments                           | 0.4.3                       | somanyenchantments+V0.4.31.jar                | None                                     |
       | LCHIJA | tc6aspects4jei                               | 0.0.2a                      | tc6aspects4jei-0.0.2a.jar                     | None                                     |
       | LCHIJA | texfix                                       | 4.0                         | TexFix+V-1.12-4.0 (1).jar                     | None                                     |
       | LCHIJA | tg                                           | 0.1.5.0                     | Thaumic_Gadgets_1.12.2_0.1.5.1_tb.26.jar      | None                                     |
       | LCHIJA | thaumicaugmentation                          | 1.12.2-1.0.6                | ThaumicAugmentation-1.12.2-1.0.6.jar          | None                                     |
       | LCHIJA | thaumicbases                                 | 3.3.310.5r                  | thaumicbases-3.3.350.6r.jar                   | None                                     |
       | LCHIJA | thaumicjei                                   | 1.6.0                       | ThaumicJEI-1.12.2-1.6.0-27.jar                | None                                     |
       | LCHIJA | thaumicperiphery                             | 0.3.0                       | thaumicperiphery-0.3.0.jar                    | None                                     |
       | LCHIJA | thaumicrestoration                           | 1.3.1                       | ThaumicRestoration-1.3.1.jar                  | None                                     |
       | LCHIJA | thaumicwonders                               | 1.7.0                       | thaumicwonders-1.7.0.jar                      | None                                     |
       | LCHIJA | trashslot                                    | 8.4.6                       | TrashSlot_1.12.1-8.4.6.jar                    | None                                     |
       | LCHIJA | uteamcore                                    | 2.2.4.94                    | u_team_core-1.12.2-2.2.4.94.jar               | None                                     |
       | LCHIJA | upsizer                                      | 4.0.1                       | upsizer-mc1.12-4.0.1.jar                      | None                                     |
       | LCHIJA | vanillafix                                   | 1.0.10-SNAPSHOT             | VanillaFix-1.0.10-99.jar                      | None                                     |
       | LCHIJA | walljump                                     | 1.12.2-1.2.3                | walljump-1.12.2-1.2.3 (1).jar                 | None                                     |
       | LCHIJA | warpbook                                     | @VERSION@                   | Warpbook-1.12.2-3.2.0.jar                     | None                                     |
       | LCHIJA | waystones                                    | 4.0.67                      | Waystones_1.12.2-4.0.67.jar                   | None                                     |
       | LCHIJA | lemonlib                                     | 1.3.0                       | lemonlib-1.12.2-1.3.0.jar                     | None                                     |
       | LCHIJA | arcaneworld                                  | 0.0.11                      | arcaneworld-1.12.2-0.0.11.jar                 | None                                     |
       | LCHIJA | orelib                                       | 3.5.2.2                     | OreLib-1.12.2-3.5.2.2.jar                     | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHIJA | dsurround                                    | 3.5.4.3                     | DynamicSurroundings-1.12.2-3.5.4.3 (1).jar    | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
  Loaded coremods (and transformers): ClientFixer (clientfixer-1.12.2-1.9.jar)
                                        com.gamerforea.clientfixer.asm.ASMTransformer
                                      CreativePatchingLoader (CreativeCore_v1.9.45_mc1.12.2.jar)
                                        
                                      HCASM (HammerCore-1.12.2-2.0.4.7.jar)
                                        com.zeitheron.hammercore.asm.HammerCoreTransformer
                                      DCLoadingPlugin (DummyCoreUnofficial-2.4.112.5.jar)
                                        DummyCore.ASM.DCASMManager
                                      SSLoadingPlugin (SereneSeasons-1.12.2-1.2.15-universal.jar)
                                        sereneseasons.asm.transformer.EntityRendererTransformer
                                        sereneseasons.asm.transformer.WorldTransformer
                                      MovingWorldCore (movingworld-1.12-6.342-full (2).jar)
                                        
                                      ForgelinPlugin (Forgelin-1.8.2.jar)
                                        
                                      CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      CosmicLibFakeCoreMod (CosmicLib-1.12.2-0.4.0.BETA.jar)
                                        
                                      TickrateChanger (TickrateChanger-1.0.14.jar)
                                        me.guichaguri.tickratechanger.TickrateTransformer
                                      BringMeTheRings plugin (BringMeTheRings-0.4.jar)
                                        zabi.minecraft.bmtr.core.BaublesTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      ItemPatchingLoader (ItemPhysic_Full_1.4.21_mc1.12.2.jar)
                                        com.creativemd.itemphysic.ItemTransformer
                                      LoadingPlugin (HardcoreDarkness-MC1.12.2-2.0.jar)
                                        lumien.hardcoredarkness.asm.ClassTransformer
                                      DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
                                        org.orecruncher.dsurround.asm.Transformer
  GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
  Hammer Core Information: FluidDictionary Info: Registered 2 fluids.
                           OreDictionary Info: Registered 699 names; 3747 stacks.
                           Pastebin Connection: Okay.
                           Dependent Mods:
                               -Thaumic Additions: Reconstructed (thaumadditions) @18r
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
                                   - chiselIntegration (Enabled/Not Forced)
  [DummyCore]: 'Special case ASM modification mods: ''Note, that these mods might not be involved in the crash in ANY WAY!''DummyCore just prints some known mods for a lot of ASM modifications''dummycore''CodeChickenLib'
  Suspected Mods: Unknown
  Launched Version: GTI
  LWJGL: 2.9.4
  OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: AntiqueAtlasExtra-v1.2.zip
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 4x Intel(R) Core(TM)2 Quad CPU Q9400 @ 2.66GHz`
Hope that this simply easy to resolve)

**Comment by Gunner76th** [comment]
@shoverno2 I know this is closed, but one thing to note here, you are not giving your modpack nearly enough ram, ESP for using Optifine. -Xmn128M -Xmx2764M  you are barely giving it 2 gigs, and with the number of mods listed, you need to be giving it a minimum of 4069M
