### ISSUE TITLE
Decrease drop rates of ender trees and golden trees

### ISSUE THREAD

**Issue by TheDeviantCrafter** [Rumaruka/Thaumic-Bases-Unofficial#23]
A single tree gives roughly 20 golden apples and 32 ender pearls. This feels a little excessive for two items that are somewhat rare in vanilla. The ideal drop rate would be 0.1 golden apples and 0.5 ender pearls per tree in my opinion.

**Comment by Rumaruka** [comment]
I don't work Thaumic bases , now .

**Comment by TheDeviantCrafter** [comment]
Is anyone else maintaining the mod?
