### ISSUE TITLE
Blaze rod recipe for cruzible is broken

### ISSUE THREAD

**Issue by Luicuelo** [Rumaruka/Thaumic-Bases-Unofficial#26]
This recipe give 3 Blaze rod for each blaze power.
dont ask for 6.

  CrucibleRecipe powderToRod= new CrucibleRecipe("TB.EXCHANG",new ItemStack(Items.BLAZE_ROD,3,0),new ItemStack(Items.BLAZE_POWDER,6,0  ),new AspectList().add(Aspect.TRAP, 8));

**Comment by S-Leader** [comment]
okay, i'll find it too...
will be fix

**Comment by S-Leader** [comment]
fixed
