### ISSUE TITLE
Tobacco crashes the game... unless you're staring at a tile entity?

### ISSUE THREAD

**Issue by JimmothyTheGreat** [Rumaruka/Thaumic-Bases-Unofficial#28]
Threw bases into the mix of one of my mudpacks, and got up to tobacco. However, whenever you try to smoke the tobacco through the pipe, once you're done the game will crash. That is it will crash unless you're staring at a chest, or something. Any help here?

**Comment by Rumaruka** [comment]
Crashlog please

**Comment by JimmothyTheGreat** [comment]
OK, I stand corrected, it doesn't crash, necessarily, it causes an internal server error, so no file to send.

Also, it only happens on multiplayer servers.

**Comment by Rumaruka** [comment]
Version addon?

**Comment by S-Leader** [comment]
fixed
