### ISSUE TITLE
When smoking in the server, the server will load class Vec2f and then kick off the player

### ISSUE THREAD

**Issue by AviatorFuchs** [Rumaruka/Thaumic-Bases-Unofficial#29]
When smoking in the server, the server will attempt to load **client-sided class Vec2f** and then get a **NoClassDefFoundError**, kicking off the player. I cannot reproduce this in the singleplayer mode.

Versions:
Baubles 1.5.2
DummyCoreUnofficial 2.4.112.5
Thaumcraft BETA26
thaumicbases 3.3.352.6r
forge 2838 (client is 2852)

These are logs logged by the server.
[latest.log](https://github.com/Rumaruka/Thaumic-Bases-Unofficial/files/4498506/latest.log) 
[debug.log](https://github.com/Rumaruka/Thaumic-Bases-Unofficial/files/4498505/debug.log)

similar one is https://github.com/Rumaruka/Thaumic-Bases-Unofficial/issues/28 , but I reproduced the issue regardless of whatever im staring at.

GIF which shows the process:
![tb1](https://user-images.githubusercontent.com/56028923/79682166-b1321500-8252-11ea-8d57-028056e6601e.gif)

**Comment by xemnes** [comment]
for me, this causes the server to crash sometimes.

**Comment by S-Leader** [comment]
Sorry to keep you waiting, fixed it
