### ISSUE TITLE
Scripts

### ISSUE THREAD

**Issue by BlackFanderra** [Rumaruka/Thaumic-Bases-Unofficial#30]
I can't remove the Thauminit armor's recipe. 
Version: 1.12.2
Mod version: 3.3.352
Delete method:
recipes.remove(<thaumicbases:thauminitehelmet>);

**Comment by Rumaruka** [comment]
recipes.remove(<thaumicbases:thauminitehelmet>) try with

**Comment by Rumaruka** [comment]
Its crafting table recipe, script must work

**Comment by BlackFanderra** [comment]
returns an error 
![image](https://user-images.githubusercontent.com/68667559/91668451-8798cc80-eb15-11ea-9226-dbe0d04dc142.png)
![image](https://user-images.githubusercontent.com/68667559/91668461-97b0ac00-eb15-11ea-820a-f18b0501d8ff.png)

**Comment by Rumaruka** [comment]
Гениально, не ставить скобки в предмет + называть скрипт русским языком , учите документацию Crafttweaker 

Close
