### ISSUE TITLE
Bug with scripts

### ISSUE THREAD

**Issue by BlackFanderra** [Rumaruka/Thaumic-Bases-Unofficial#31]
Чел, я понимаю, что у тебя беда с башкой, и ты удаляешь свои же ответы, но прошу о помощи вновь. То, что файл скрипта назван на русском - ничего не меняет. У меня с русскими названиями работают все скрипты, и лишь с этим аддоном не работает. Поменял на англ. название - не помогло (и не должно было, как и со скобочками). Так в чём же может быть проблема?

**Comment by BlackFanderra** [comment]
Забыл ещё сказать: у косы белоглазого нет текстуры на 1.12.2. И, поскольку ты у нас уникальный случай, то напомню: версия мода 3.3.352.6

**Comment by Rumaruka** [comment]
Про косу я знаю , остальное это уже твои неназнания в скриптах , читай документацию!

**Comment by Zeitheron** [comment]
🤡

**Comment by BlackFanderra** [comment]
У меня уже больше сотни крафтов на обработчиках разных модов, в том числе в тауме куча крафтов наполнения, тигеля и мистического верстака. В других аддонах к тауму всё также работает, только этот аддон дал сбой. Документацию я уже и так прекрасно знаю, и могу сказать точно: ошибка не на моей стороне. И да, в ThaumicBases я уже тоже делал крафты, и всё работало. Только тауминитовая броня не работает.

**Comment by perevozke** [comment]
Есть один скрипт, убирающий как крафт кровавой брони, так и тауминитовой, но по неизвестным причинам крафт первой удаляется, второй - нет. Ошибки после этого никакой не следует, пробовал разные способы, функционал не наблюдается, клоунада на твоей стороне

**Comment by Rumaruka** [comment]
Это обычный крафт и как вы мне прикажете фиксить  -_- проверяйте свои скрипты это единственное , что вам скажу

**Comment by perevozke** [comment]
ну единственное различие между двумя этими арморами - один крафтится на аркан верстаке, второй обычном верстаке, сейчас удаляю крафт рандомной вещице из твоего мода, которая крафтится на верстаке, если не удалится то все же проблема с крафтами на верстаках

**Comment by perevozke** [comment]
reсipes.remove(<thaumicbases:irongreatwood>); (обрамлённое железом великое дерево) - крафт не удалился, тауминитовый меч тоже, проблема с крафтами на обычном верстаке, тигель/наполнение/аркан верстак спокойно удаляет

**Comment by perevozke** [comment]
удалились <> в скобках выше

**Comment by Rumaruka** [comment]
Странно , я гляну. Никто просто скрипты не репортил, поэтому и показалось странным.

**Comment by perevozke** [comment]
версия майна 1.12.2, мода 3.3.352.6r

**Comment by Rumaruka** [comment]
> удалились <> в скобках выше

Я думал, вы без скобках писали XD , хорошо я посмотрю

**Comment by Rumaruka** [comment]
> версия майна 1.12.2, мода 3.3.352.6r

Уже сказали выше

**Comment by Rumaruka** [comment]
> reсipes.remove(thaumicbases:irongreatwood); (обрамлённое железом великое дерево) - крафт не удалился, тауминитовый меч тоже, проблема с крафтами на обычном верстаке, тигель/наполнение/аркан верстак спокойно удаляет

А ещё файл скрипта можно ?

**Comment by perevozke** [comment]
файл нельзя, можно текстом/куда-то в лс

**Comment by BlackFanderra** [comment]
Гитхаб не поддерживает .zs, могу кинуть pdf

**Comment by BlackFanderra** [comment]
[Тауминитовая броня.pdf](https://github.com/Rumaruka/Thaumic-Bases-Unofficial/files/5147595/default.pdf)

**Comment by Rumaruka** [comment]
Хорошо, простите, что так среагировал. Никогда просто такого не было.

**Comment by Rumaruka** [comment]
Нашел ошибку!
Скоро поправлю, насчет косы - я хотел сделать 3d модель, но передумал, верну ее в 2d 
Спасибо
Все из за того, что все крафты Shapless и система не понимала, что именно удалять

**Comment by Rumaruka** [comment]
Исправлены крафты, теперь их можно удалять!
В 3.3.360.6r

Close #31

**Comment by perevozke** [comment]
рофл, удалил крафт шлема, крафт остался, но изменился рецепт пустотных ножниц, у них теперь пустой крафт 
![unknown](https://user-images.githubusercontent.com/68667665/91716156-bc4d6800-eb97-11ea-8900-32a8bb979eac.png)
![unknow1n](https://user-images.githubusercontent.com/68667665/91716188-c8392a00-eb97-11ea-9c3e-8dc3db687c51.png)

**Comment by Rumaruka** [comment]
"удалил крафт шлема, крафт остался"
Не должно уже быть, я проверял, все работает, кроме shapeless

**Comment by perevozke** [comment]
recipes.remove(<thaumicbases:thauminitehelmet>); перед этим вот это
// Кровавые поножи тауматурга
mods.thaumcraft.ArcaneWorkbench.removeRecipe(<thaumicbases:bloodylegs>);
mods.thaumcraft.ArcaneWorkbench.registerShapedRecipe("BloodFabric", "TB.BloodFabric", 50, [<aspect:aqua>*5], <thaumicbases:bloodylegs>,
    [[<thaumicbases:bloodycloth>, <forge:bucketfilled>.withTag({FluidName: "lifeessence", Amount: 1000}), <thaumicbases:bloodycloth>],
    [<thaumadditions:crystal_block>.withTag({Aspect: "victus"}), <thaumicbases:thauminitelegs>, <thaumadditions:crystal_block>.withTag({Aspect: "victus"})],
    [<thaumicbases:bloodycloth>, <grimoireofgaia:accessory_cursed>, <thaumicbases:bloodycloth>]]);

Шлем не удалился, крафт понож старый удалился

**Comment by Rumaruka** [comment]
Вы точно обновились?
`recipes.remove(<thaumicbases:thauminitehelmet>);

recipes.remove(<thaumicbases:thauminiteaxe>);` 
Когда я менял крафты - работал

**Comment by perevozke** [comment]
да, сегодня утром обновлялся до новой версии, вы пробовали именно тауминитовую броню?

**Comment by Rumaruka** [comment]
![image](https://user-images.githubusercontent.com/8148679/91717974-f88ac380-ebab-11ea-968e-7454bb33b19b.png)
![image](https://user-images.githubusercontent.com/8148679/91717993-00e2fe80-ebac-11ea-9b48-b0fee7b9c0b1.png)
![image](https://user-images.githubusercontent.com/8148679/91718007-06d8df80-ebac-11ea-93ad-eb53e5e8a30d.png)
![image](https://user-images.githubusercontent.com/8148679/91718029-0b9d9380-ebac-11ea-8784-e36203522492.png)

**Comment by perevozke** [comment]
вы просто прописали 
recipes.remove(<thaumicbases:thauminitehelmet>);?
и с <> или без?

**Comment by perevozke** [comment]
скиньте код, если можно

**Comment by Rumaruka** [comment]
https://pastebin.com/P873R4Pn

**Comment by perevozke** [comment]
странно, сейчас попробую

**Comment by BlackFanderra** [comment]
![image](https://user-images.githubusercontent.com/68667559/91718798-c887f400-eb9c-11ea-90fd-691e0880c919.png)
![image](https://user-images.githubusercontent.com/68667559/91718817-d0479880-eb9c-11ea-9a1b-70e2461bd8da.png)
![image](https://user-images.githubusercontent.com/68667559/91718833-d50c4c80-eb9c-11ea-9c9c-afd64cde295d.png)
и всё остальное тоже не удалилось. Мод точно обновил
![image](https://user-images.githubusercontent.com/68667559/91718886-f3724800-eb9c-11ea-8279-045e6206131e.png)

**Comment by Rumaruka** [comment]
Только, что проверил не с IDEA, все также... я проверяю дальше

**Comment by Rumaruka** [comment]
Возможно проблема из за старого АПИ крафта, ну большое время, чтобы переписать всю систему крафта.
К сожалению, у меня сейчас нет времени заниматься =(
Я был уверен, что я все исправил

**Comment by perevozke** [comment]
если что, напишите в телегу @kybeer или @BlackFanderra (и да, мы знаем что она у вас есть, когда прода?)

**Comment by BlackFanderra** [comment]
На какие сроки фикса мы вообще можем расcчитывать?

**Comment by Rumaruka** [comment]
К сожалению, их нет. Слишком много работы в офисе и ИРЛ. Просто следите , как будут силы так сделаю. А сейчас все силы брошены на приоритетные дела и моды в них не входят

**Comment by Rumaruka** [comment]
Исправил
