### ISSUE TITLE
Empty recipe for Void Shears

### ISSUE THREAD

**Issue by Shattered2909** [Rumaruka/Thaumic-Bases-Unofficial#32]
![2020-09-03_20 50 28](https://user-images.githubusercontent.com/35029480/92155089-1d3e9f80-ee27-11ea-9008-de3a4db795df.png)

For some reason Thaumic Bases is creating this empty recipe for Void Shears which allows just getting them out of nothing, I wasn't able to remove it with Crafttweaker, very odd.

**Comment by Rumaruka** [comment]
I rewrite mod for stable mapping , but I don't have time for it

**Comment by mxnmnm** [comment]
Are there any other good ways to fix this?

**Comment by Rumaruka** [comment]
Yes, I Know (probably) how fix this, but I haven't time

**Comment by mxnmnm** [comment]
Is there something such as crafttweaker (which like said above doesn't work ;-;) that would manage to fix this or would the fix 100% have to be on your end and there is no other way around it?

**Comment by Rumaruka** [comment]
Just wait

**Comment by Rumaruka** [comment]
Fixed
Close #32
