### ISSUE TITLE
[Bugs] Everything wrong about plants (or almost everything)

### ISSUE THREAD

**Issue by shoverno2** [Rumaruka/Thaumic-Bases-Unofficial#35]
Plants are not register like other plants
Being incompatible with almost any mod that's about farming or tweaking 

And same with trees
more over
Having broken texture. Their leaves not registered like leaves

and everything highly affected by luck enchantment

I think to fix that all...
It needed to be added again with vanilla patern, I guess

+"Sugar cane wild plant" broken too
And growing only in one direction

**Comment by S-Leader** [comment]
all fixed
