### ISSUE TITLE
Seed Not Growing

### ISSUE THREAD

**Issue by jjdamstra** [Rumaruka/Thaumic-Bases-Unofficial#6]
So far I've planted the sweed seeds and the metalleat seeds and neither are growing. The only was to to make them grow is applying bonemeal. I am using thaumicbases-3.1.255.2r-ForTC6B17 with Thaumcraft 6 B19 forge 14.23.4.2745

**Comment by Rumaruka** [comment]
Seeds growing very very very very slow

**Comment by jjdamstra** [comment]
Okay so if you don't mind me asking what is considered very very very very slow. I planted them more than 24 hrs ago(Real world time) and they have not grown at all. Not even the sweed which in the book says it rapidly spreads. I do have on sweed that I fully grown with bonemeal and one that hasn't grown at all and neither seem to be spreading

**Comment by Rumaruka** [comment]
Sweed , i think useless plant =)

**Comment by jjdamstra** [comment]
So should the other seeds like metalleat and void seeds take more than 24 world hrs to grow?? And I mean they haven't even grow past the very first stage.

**Comment by Rumaruka** [comment]
I forgot , maybe 32 ingame day

**Comment by Rumaruka** [comment]
Fix
Seeds DON`T GROWING
My mistake
