### ISSUE TITLE
Crash while using the Overchanting Table

### ISSUE THREAD

**Issue by angelnc1989** [Rumaruka/Thaumic-Bases-Unofficial#8]
Minecraft 1.12.2
Forge 14.23.4.2759
Thaumcraft 6.1 BETA24
Thaumic Bases 3.2.255.2r

https://pastebin.com/cKD13XEH

**Comment by Rumaruka** [comment]
Thaumic Bases 3.2.255.2r update to  3.2.255.2r-ForTC6B21

**Comment by angelnc1989** [comment]
That's the version I'm on

**Comment by Rumaruka** [comment]
Hmm i don`t cluth this bugs.... strange

**Comment by Rumaruka** [comment]
Close #8 need more infomation

**Comment by angelnc1989** [comment]
No idea why you are closing the issue.
This crash occurs randomly while the Overchanting Table is enchanting an item. It doesn't happen every time and there is no indicator on when it exactly happens.

**Comment by Rumaruka** [comment]
If you found new error tell me more and make more experiments for table
