### ISSUE TITLE
Tobacco Recipe Tree Bugs

### ISSUE THREAD

**Issue by LazerusKI** [Rumaruka/Thaumic-Bases-Unofficial#9]
Found a few issues with it, as mentioned in the comment already

- Tobacco needs Messis which isnt available at the moment
- The Silverwood Pipe needs Sano which also isnt available
- In the infusion process, you cant put the Greatwood pipe on the altar, which makes the Silverwood pipe unobtainable

**Comment by LazerusKI** [comment]
and one more, more like a quality improvement though.

The Tobacco entries are all messed up, there are no line or page breaks between the different types. would be great if each type would have its own page.
there is also no description for what the different pipes do as far as i could see (same with the fire magic tab btw, it only describes the brazier related to the campfire, but i have no idea what even the campfire does)

**Comment by Rumaruka** [comment]
"Tobacco needs Messis which isnt available at the moment
The Silverwood Pipe needs Sano which also isnt available"
Fix, but 
I don`t setup infusion system. I don`t know why.....
"In the infusion process, you cant put the Greatwood pipe on the altar, which makes the Silverwood pipe unobtainable" I don`t know, but this Right click don`t working. Use hopper

**Comment by Rumaruka** [comment]
Tobacco needs Messis which isnt available at the moment
The Silverwood Pipe needs Sano which also isnt available
Dupe #7 
FIX
In the infusion process, you cant put the Greatwood pipe on the altar, which makes the Silverwood pipe unobtainable
Use Hopper

Thank you for report bugs
Close #9
